### ISSUE TITLE
missing forwardable dependency

### ISSUE THREAD

**Issue by svanzoest** [zeisler/active_mocker#121]
with ruby 2.5.5 I am getting errors as follows:

```ruby
Failure/Error: require "active_mocker/rspec_helper"

NameError:
  uninitialized constant #<Class:ActiveMocker::LoadedMocks>::Forwardable
# ./spec/spec_helper.rb:11:in `require'
# ./spec/spec_helper.rb:11:in `<top (required)>'
# ./spec/rails_helper.rb:3:in `require'
# ./spec/rails_helper.rb:3:in `<top (required)>'
# ./spec/requests/updates_spec.rb:1:in `require'
# ./spec/requests/updates_spec.rb:1:in `<top (required)>'
```

when running `bundle exec rspec`. It seems like the `forwardable` gem is missing from the `Gemfile`/`.gemspec`?

`ruby -e "require 'rspec';require 'active_mocker/rspec_helper'"` fails with
```ruby
Traceback (most recent call last):
	10: from -e:1:in `<main>'
	 9: from /Users/svanzoest/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 8: from /Users/svanzoest/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	 7: from /Users/svanzoest/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	 6: from /Users/svanzoest/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/active_mocker-2.6.0/lib/active_mocker/rspec_helper.rb:2:in `<top (required)>'
	 5: from /Users/svanzoest/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	 4: from /Users/svanzoest/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	 3: from /Users/svanzoest/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/active_mocker-2.6.0/lib/active_mocker/loaded_mocks.rb:4:in `<top (required)>'
	 2: from /Users/svanzoest/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/active_mocker-2.6.0/lib/active_mocker/loaded_mocks.rb:5:in `<module:ActiveMocker>'
	 1: from /Users/svanzoest/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/active_mocker-2.6.0/lib/active_mocker/loaded_mocks.rb:6:in `<class:LoadedMocks>'
/Users/svanzoest/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/active_mocker-2.6.0/lib/active_mocker/loaded_mocks.rb:7:in `singleton class': uninitialized constant #<Class:ActiveMocker::LoadedMocks>::Forwardable (NameError)
```
Adding `forwardable` seems to fix it.
`ruby -e "require 'forwardable';require 'rspec';require 'active_mocker/rspec_helper'"`

**Comment by zeisler** [comment]
It looks like it's missing a require in this file [lib/active_mocker/loaded_mocks.rb](https://github.com/zeisler/active_mocker/blob/master/lib/active_mocker/loaded_mocks.rb). Do you, @svanzoest mind opening a PR and adding this line to the top of the file `require "forwardable"`

**Comment by svanzoest** [comment]
@zeisler I haven't had a chance to test the change much, but I created #122
