### ISSUE TITLE
Enable use of alias_method_chain on Relations

### ISSUE THREAD

**Issue by markburns** [zeisler/active_mocker#45]
Sorry for lack of test isolation case so far. This is on latest master of active_mocker.

In a class Foo with `some_aliased_method` aliased, a stack trace like this results

```
undefined method `some_aliased_method' for class `#<Module:0x007fb502d53c98>::Foo'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
/Users/markburns/code/some_rails_app/app/models/foo.rb:337:in `<class:Foo>'
/Users/markburns/code/some_rails_app/app/models/foo.rb:1:in `call'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dissociated_introspection-0.4.1/lib/dissociated_introspection/eval_sandbox.rb:13:in `module_eval'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dissociated_introspection-0.4.1/lib/dissociated_introspection/eval_sandbox.rb:13:in `call'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dissociated_introspection-0.4.1/lib/dissociated_introspection/inspection.rb:90:in `load_sandbox'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dissociated_introspection-0.4.1/lib/dissociated_introspection/inspection.rb:86:in `get_sandbox_class'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dissociated_introspection-0.4.1/lib/dissociated_introspection/inspection.rb:15:in `get_class'
/Users/markburns/code/active_mocker/lib/active_mocker/mock_creator.rb:132:in `constants'
(erb):2:in `block in partials'
```

**Comment by zeisler** [comment]
Can isolate this down to the minimum ActiveRecord model code that causes the issue?

**Comment by markburns** [comment]
Closing as have seen working in an isolated app and am guessing it is down to some very specific peculiarity of our app

**Comment by markburns** [comment]
Managed to replicate. I mean, it is a bit crazy code, so not sure how easy it is to support, but here it is:

```ruby
ActiveRecord::Schema.define(version: 20160427124939) do
  create_table "bars", force: :cascade do |t|
    t.integer  "foo_id"
    t.string   "some_other_attribute"
  end

  create_table "foos", force: :cascade do |t|
    t.string   "some_attribute"
  end
end

class Foo < ActiveRecord::Base
  has_one :bar

  def bar_with_default
    bar = bar_without_default
    return bar if bar
    Bar.new(some_other_attribute: "Some default bar attribute")
  end
  alias_method_chain :bar, :default
end

class Bar < ActiveRecord::Base
end

```


```
ERROR_VERBOSITY=3 spring rake active_mocker:build                                                                                                                                                                    [2.3.0]
Running via Spring preloader in process 35809
Generating Mocks |======================================================>>| 100%
Foo has the following errors:
undefined method `bar' for class `#<Module:0x007f895ddfc648>::Foo'
error
undefined method `bar' for class `#<Module:0x007f895ddfc648>::Foo'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
/Users/markburns/code/delete_me/app/models/foo.rb:10:in `<class:Foo>'
/Users/markburns/code/delete_me/app/models/foo.rb:1:in `call'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dissociated_introspection-0.4.1/lib/dissociated_introspection/eval_sandbox.rb:13:in `module_eval'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dissociated_introspection-0.4.1/lib/dissociated_introspection/eval_sandbox.rb:13:in `call'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dissociated_introspection-0.4.1/lib/dissociated_introspection/inspection.rb:90:in `load_sandbox'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dissociated_introspection-0.4.1/lib/dissociated_introspection/inspection.rb:86:in `get_sandbox_class'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dissociated_introspection-0.4.1/lib/dissociated_introspection/inspection.rb:15:in `get_class'
/Users/markburns/code/active_mocker/lib/active_mocker/mock_creator.rb:132:in `constants'
(erb):2:in `block in partials'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
/Users/markburns/code/active_mocker/lib/active_mocker/mock_creator.rb:103:in `block in partials'
/Users/markburns/code/active_mocker/lib/active_mocker/mock_creator.rb:99:in `each'
/Users/markburns/code/active_mocker/lib/active_mocker/mock_creator.rb:99:in `each_with_object'
/Users/markburns/code/active_mocker/lib/active_mocker/mock_creator.rb:99:in `partials'
(erb):7:in `template_creator_default'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
/Users/markburns/.rbenv/versions/2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
/Users/markburns/code/active_mocker/lib/active_mocker/template_creator.rb:15:in `render'
/Users/markburns/code/active_mocker/lib/active_mocker/mock_creator.rb:29:in `create'
/Users/markburns/code/active_mocker/lib/active_mocker/generate.rb:69:in `create_mock'
/Users/markburns/code/active_mocker/lib/active_mocker/generate.rb:39:in `block in do_stuff'
/Users/markburns/code/active_mocker/lib/active_mocker/generate.rb:37:in `open'
/Users/markburns/code/active_mocker/lib/active_mocker/generate.rb:37:in `do_stuff'
/Users/markburns/code/active_mocker/lib/active_mocker/generate.rb:21:in `block in call'
/Users/markburns/code/active_mocker/lib/active_mocker/generate.rb:20:in `each'
/Users/markburns/code/active_mocker/lib/active_mocker/generate.rb:20:in `each_with_index'
/Users/markburns/code/active_mocker/lib/active_mocker/generate.rb:20:in `call'
/Users/markburns/code/active_mocker/lib/active_mocker/public_methods.rb:30:in `create_mocks'
/Users/markburns/code/active_mocker/lib/active_mocker/task.rake:12:in `block (2 levels) in <top (required)>'
```

**Comment by zeisler** [comment]
Thanks for the repo steps. The change will need to be made in [dissociated_introspection](https://github.com/zeisler/dissociated_introspection). This should not be a difficult change.

**Comment by zeisler** [comment]
@markburns can you try this out on latest master?
